version: '2'

services:
  postgres:
    build:
      context: ./dep/
      dockerfile: postgres.dockerfile
    env_file: ./dep/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - ./dep/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - cc_network

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "8000:8080"
    networks:
      - cc_network

  cc_build:
    build:
      context: ./dep/
      dockerfile: node.dockerfile

  cc_tests:
    build:
      context: ../
      dockerfile: ./docker/cc_api.dockerfile
    volumes:
      - ../:/app/src:rw
    command: ["npm", "run", "test"]

  cc_deploy:
    build:
      context: ../
      dockerfile: ./docker/cc_api.dockerfile
    volumes:
      - ../:/app/src:rw
    ports:
      - "8080:8080"
    command: ["node", "index.js"]
    # command: ["tail", "-f", "/dev/null"]
    networks:
      - cc_network

volumes:
  dbdata:

networks:
    cc_network:
